name: CI Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # JDK version
          distribution: 'temurin' # JDK distributions (temurin, zulu etc.)
          cache: gradle

      # 3. Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Run Gradle build
      - name: Run Gradle Build
        run: ./gradlew clean test

      # 5. Code coverage(Codecov)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: ${{ github.repository }} # GitHub repo
          files: build/jacoco/coverage.xml # JaCoCo XML path
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov token (in Codecov Project Settings)
          flags: unittests
          name: codecov-coverage

      # 6. HTML reports
      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/jacoco/coverage
