name: CI Build

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # JDK version
          distribution: 'temurin' # JDK distributions (temurin, zulu etc.)
          cache: gradle

      - name: Run Gradle Build
        run: ./gradlew clean build

      - name: Publish to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }} # release branch only
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # GPG private key
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # GPG passphrase
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }} # given by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # given by GitHub
        run: ./gradlew publishToGithub

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: ${{ github.repository }} # GitHub repo
          files: build/jacoco/coverage.xml # JaCoCo XML path
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov token (in Codecov Project Settings)
          flags: unittests
          name: codecov-coverage

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: build/reports/tests/test
