name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # JDK version
          distribution: 'temurin' # JDK distributions (temurin, zulu etc.)
          cache: gradle

      # 3. Run Gradle test
      - name: Run Gradle Build
        run: ./gradlew clean test

      # 4. publish to GitHub Packages
      - name: Publish to GitHub Packages
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # GPG private key
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # GPG passphrase
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }} # given by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # given by GitHub
        run: ./gradlew publishToGithub

      # 5. publish to Maven Central
      - name: Publish to Maven Central
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # GPG private key
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # GPG passphrase
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSS_USERNAME }} # given by Sonatype
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSS_PASSWORD }} # given by Sonatype
        run: ./gradlew publishToMavenCentral

      # 6. Code coverage(Codecov)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: ${{ github.repository }} # GitHub repo
          files: build/jacoco/coverage.xml # JaCoCo XML path
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov token (in Codecov Project Settings)
          flags: unittests
          name: codecov-coverage

      # 7. HTML reports
      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: build/reports/tests/test
